Repository minio/minsql, pull requests merged in 2019-07, with the labels that each got.

#93 add build dependencies to README.md
  README.md
Labels: dependencies

#92 Improve Query Processing
  src/filter.rs
  src/query.rs
Labels: bug

#95 Read multiple Datastores concurrently for queries
  src/combinators/mod.rs
  src/combinators/take_from_iterable.rs
  src/lib.rs
  src/query.rs
  src/storage.rs
Labels: enhancement

#99 Update Dependencies
  Cargo.lock
  Cargo.toml
Labels: dependencies

#100 Update Rusoto to 0.40.0
  Cargo.lock
  Cargo.toml
  src/meta.rs
  src/storage.rs
Labels: dependencies

#102 Configuration via environment variables
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  src/auth.rs
  src/config.rs
  src/filter.rs
  src/http.rs
  src/lib.rs
  src/meta.rs
  src/query.rs
  src/storage.rs
Labels: enhancement

#105 Listen for config changes on the Metabucket
  Cargo.lock
  Cargo.toml
  src/api/api_datastores.rs
  src/api/mod.rs
  src/http.rs
  src/lib.rs
  src/meta.rs
  src/query.rs
  src/storage.rs
Labels: enhancement

#106 Logs API
  src/api/logs.rs
  src/api/mod.rs
  src/config.rs
  src/http.rs
  src/lib.rs
Labels: enhancement

#108 Auth and Token API
  README.md
  src/api/api_datastores.rs
  src/api/auth.rs
  src/api/datastores.rs
  src/api/logs.rs
  src/api/mod.rs
  src/api/tokens.rs
  src/auth.rs
  src/config.rs
  src/filter.rs
  src/http.rs
  src/meta.rs
  src/query.rs
  src/storage.rs
Labels: bug, enhancement

#115 Perform Multiple List Objects for metabucket load
  src/meta.rs
Labels: bug

#116 APIs require token in headers
  Cargo.lock
  Cargo.toml
  src/api/auth.rs
  src/api/datastores.rs
  src/api/logs.rs
  src/api/mod.rs
  src/api/tokens.rs
  src/http.rs
  src/ingest.rs
  src/lib.rs
  src/query.rs
Labels: bug, enhancement

#122 Format results as line JSON
  src/query.rs
Labels: enhancement

#121 Header to have server return preview of query results
  src/query.rs
Labels: enhancement

#124 Support new entities
  Cargo.lock
  Cargo.toml
  README.md
  src/constants.rs
  src/filter.rs
  src/query.rs
Labels: enhancement
